In [1]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd

df = pd.read_excel("Zara_Sales_Analysis.csv.xlsx")

df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [5]:
df.shape

(252, 16)

In [6]:
df.shape

(252, 16)

In [7]:
 df.columns

Index(['Product ID', 'Product Position', 'Promotion', 'Product Category',
       'Seasonal', 'Sales Volume', 'brand', 'url', 'sku', 'name',
       'description', 'price', 'currency', 'scraped_at', 'terms', 'section'],
      dtype='object')

In [8]:
df.columns

Index(['Product ID', 'Product Position', 'Promotion', 'Product Category',
       'Seasonal', 'Sales Volume', 'brand', 'url', 'sku', 'name',
       'description', 'price', 'currency', 'scraped_at', 'terms', 'section'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product ID        252 non-null    int64
 1   Product Position  252 non-null    object
 2   Promotion         252 non-null    object
 3   Product Category  252 non-null    object
 4   Seasonal          252 non-null    object
 5   Sales Volume      252 non-null    int64
 6   brand             252 non-null    object
 7   url               252 non-null    object
 8   sku               252 non-null    object
 9   name              251 non-null    object
 10  description       250 non-null    object
 11  price             252 non-null    float64
 12  currency          252 non-null    object
 13  scraped_at        252 non-null    object
 14  terms             252 non-null    object
 15  section           252 non-null    object
dtypes: float64(1), int64(2), object(13)
memory usage: 31.6+ KB

In [10]:
df = df.drop(columns=['url','description','sku','scraped_at'])

In [11]:
df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,name,price,currency,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,BASIC PUFFER JACKET,19.99,USD,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,TUXEDO JACKET,169.00,USD,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,SLIM FIT SUIT JACKET,129.00,USD,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,STRETCH SUIT JACKET,129.00,USD,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,DOUBLE FACED JACKET,139.00,USD,jackets,MAN

In [12]:
df = df.dropna(subset=['name'])

In [13]:
df = df.dropna(subset=['name'])

In [14]:
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Product Category    0
Seasonal            0
Sales Volume        0
brand               0
name                0
price               0
currency            0
terms               0
section             0
dtype: int64

In [15]:
df = df.rename(columns={
'Product ID':'product_id',
'Product Position':'product_position',
'Promotion':'promotion',
'Product Category':'product_category',
'Seasonal':'seasonal',
'Sales Volume':'sales_volume'
})

In [16]:
df.columns

Index(['product_id', 'product_position', 'promotion', 'product_category',
       'seasonal', 'sales_volume', 'brand', 'name', 'price', 'currency',
       'terms', 'section'],
      dtype='object')

In [17]:
df.sort_values(by='sales_volume',ascending=False).head(10)

,product_id,product_position,promotion,product_category,seasonal,sales_volume,brand,name,price,currency,terms,section
125,183825,Aisle,Yes,Clothing,Yes,2989,Zara,PLAID TIE DYE OVERSHIRT,19.99,USD,jackets,MAN
237,123047,Aisle,No,Clothing,Yes,2985,Zara,SUIT JACKET IN 100% LINEN,109.00,USD,t-shirts,MAN
246,113435,Aisle,No,Clothing,Yes,2973,Zara,RIB COLLAR JACKET,129.00,USD,jackets,MAN
5,117590,End-cap,No,Clothing,No,2968,Zara,CONTRASTING COLLAR JACKET,79.90,USD,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,DOUBLE FACED JACKET,139.00,USD,jackets,MAN
34,172364,Aisle,Yes,Clothing,No,2931,Zara,FAUX LEATHER BOMBER JACKET,109.00,USD,jackets,MAN
66,137990,Aisle,No,Clothing,No,2929,Zara,COTTON JACKET,29.99,USD,jackets,MAN
204,134429,Aisle,No,Clothing,No,2914,Zara,RIPPED STRAIGHT FIT JEANS,69.90,USD,jeans,MAN
181,171520,End-cap,Yes,Clothing,Yes,2901,Zara,GATHERED WAIST KNIT SWEATER,47.90,USD,sweaters,WOMAN
206,136272,End-cap,No,Clothing,Yes,2887,Zara,PURL KNIT SWEATER,12.99,USD,sweaters,MAN

In [18]:
df['price'].mean()

np.float64(86.08223107569721)

In [19]:
df.groupby('product_category')['sales_volume'].sum()

product_category
Clothing    457735
Name: sales_volume, dtype: int64

In [21]:
df.groupby('seasonal')['sales_volume'].sum()

seasonal
No     224554
Yes    233181
Name: sales_volume, dtype: int64

In [22]:
df.to_csv("zara_clean_data.csv",index=False)

In [23]:
df.describe()

          product_id  sales_volume       price
count     251.000000    251.000000  251.000000
mean   153290.003984   1823.645418   86.082231
std     26181.420512    699.097176   52.116910
min    110075.000000    529.000000    7.990000
25%    130809.500000   1241.000000   49.900000
50%    151438.000000   1841.000000   79.900000
75%    175755.500000   2400.500000  109.000000
max    199631.000000   2989.000000  439.000000

In [24]:
df['product_category'].value_counts()

product_category
Clothing    251
Name: count, dtype: int64

In [25]:
import os
os.listdir()

['.ipynb_checkpoints',
 'zara_clean_data.csv',
 'zara_data_cleaning_and_eda..ipynb',
 'Zara_Sales_Analysis.csv.xlsx']

In [26]:
df.shape

(251, 12)

In [27]:
test = pd.read_csv("zara_clean_data.csv")
test.shape

(251, 12)

In [28]:
df['terms'].value_counts().head(20)

terms
jackets     139
sweaters     41
t-shirts     32
shoes        31
jeans         8
Name: count, dtype: int64

In [29]:
df['category'] = df['terms']

In [30]:
    df['category'].value_counts()

category
jackets     139
sweaters     41
t-shirts     32
shoes        31
jeans         8
Name: count, dtype: int64

In [31]:
df.groupby('category')['sales_volume'].sum().sort_values(ascending=False)

category
jackets     257630
sweaters     75242
shoes        57906
t-shirts     53637
jeans        13320
Name: sales_volume, dtype: int64

In [32]:
df[['name','category','sales_volume']].sort_values(by='sales_volume',ascending=False).head(10)

                            name  category  sales_volume
125      PLAID TIE DYE OVERSHIRT   jackets          2989
237    SUIT JACKET IN 100% LINEN  t-shirts          2985
246            RIB COLLAR JACKET   jackets          2973
5      CONTRASTING COLLAR JACKET   jackets          2968
4            DOUBLE FACED JACKET   jackets          2942
34    FAUX LEATHER BOMBER JACKET   jackets          2931
66                 COTTON JACKET   jackets          2929
204    RIPPED STRAIGHT FIT JEANS     jeans          2914
181  GATHERED WAIST KNIT SWEATER  sweaters          2901
206            PURL KNIT SWEATER  sweaters          2887

In [33]:
df.groupby('category')['price'].mean().sort_values(ascending=False)

category
jackets     105.590719
t-shirts     67.427813
shoes        64.873548
jeans        63.923750
sweaters     54.862683
Name: price, dtype: float64

In [34]:
df.groupby('promotion')['sales_volume'].sum()

promotion
No     240312
Yes    217423
Name: sales_volume, dtype: int64

In [35]:
df.groupby('seasonal')['sales_volume'].sum()

seasonal
No     224554
Yes    233181
Name: sales_volume, dtype: int64

In [36]:
df.to_csv("zara_final_dataset.csv",index=False)

In [37]:
df.groupby('category')['sales_volume'].sum()

category
jackets     257630
jeans        13320
shoes        57906
sweaters     75242
t-shirts     53637
Name: sales_volume, dtype: int64

In [38]:
category_sales = df.groupby('category')['sales_volume'].sum()

category_percent = (category_sales / category_sales.sum()) * 100

category_percent

category
jackets     56.283658
jeans        2.909981
shoes       12.650551
sweaters    16.437895
t-shirts    11.717915
Name: sales_volume, dtype: float64

In [39]:
df[['name','category','sales_volume','price']].sort_values(
by='sales_volume',ascending=False).head(10)

                            name  category  sales_volume   price
125      PLAID TIE DYE OVERSHIRT   jackets          2989   19.99
237    SUIT JACKET IN 100% LINEN  t-shirts          2985  109.00
246            RIB COLLAR JACKET   jackets          2973  129.00
5      CONTRASTING COLLAR JACKET   jackets          2968   79.90
4            DOUBLE FACED JACKET   jackets          2942  139.00
34    FAUX LEATHER BOMBER JACKET   jackets          2931  109.00
66                 COTTON JACKET   jackets          2929   29.99
204    RIPPED STRAIGHT FIT JEANS     jeans          2914   69.90
181  GATHERED WAIST KNIT SWEATER  sweaters          2901   47.90
206            PURL KNIT SWEATER  sweaters          2887   12.99

In [40]:
df[['price','sales_volume']].corr()

                 price  sales_volume
price         1.000000     -0.071522
sales_volume -0.071522      1.000000

In [41]:
df.groupby('promotion')['sales_volume'].mean()

promotion
No     1820.545455
Yes    1827.084034
Name: sales_volume, dtype: float64

In [42]:
df.to_csv("zara_sales_final.csv",index=False)

In [43]:
import os
os.listdir()

['.ipynb_checkpoints',
 'zara_clean_data.csv',
 'zara_data_cleaning_and_eda..ipynb',
 'zara_final_dataset.csv',
 'Zara_Sales_Analysis.csv.xlsx',
 'zara_sales_final.csv']

In [44]:
import os
os.getcwd()

'C:\\Users\\harsh\\zara-product-analytics'